"""
Django settings for library_system project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# 导入Path类，用于处理文件路径
from pathlib import Path

# 定义项目基础目录，指向项目根目录（settings.py所在目录的父目录）
BASE_DIR = Path(__file__).resolve().parent.parent


# 快速开发设置 - 不适合生产环境
# 参考文档: https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# 安全警告：生产环境中必须保密的密钥，用于加密会话和其他安全相关功能
SECRET_KEY = 'django-insecure-odmh356f(dx8c0-n@hbyx2^xyxk&!1^3woerot0@^!v8hy5+h@'

# 调试模式开关，开发环境设为True，生产环境必须设为False
DEBUG = True

# 允许访问的主机列表，空列表表示只允许本地访问
ALLOWED_HOSTS = ['*']


# 应用定义
INSTALLED_APPS = [
    'django.contrib.admin',          # Django自带的管理后台应用
    'django.contrib.auth',           # 用户认证系统
    'django.contrib.contenttypes',   # 内容类型框架
    'django.contrib.sessions',       # 会话管理
    'django.contrib.messages',       # 消息框架
    'django.contrib.staticfiles',    # 静态文件管理
    'books',                         # 自定义的图书管理应用
]

# 中间件配置，处理HTTP请求和响应的中间层
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',      # 安全中间件，处理安全相关设置
    'django.contrib.sessions.middleware.SessionMiddleware', # 会话中间件，管理用户会话
    'django.middleware.common.CommonMiddleware',          # 通用中间件，处理常见HTTP功能
    'django.middleware.csrf.CsrfViewMiddleware',          # CSRF保护中间件
    'django.contrib.auth.middleware.AuthenticationMiddleware', # 用户认证中间件
    'django.contrib.messages.middleware.MessageMiddleware',    # 消息中间件
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # 点击劫持保护
]

# 根URL配置文件路径
ROOT_URLCONF = 'library_system.urls'

# 模板配置
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  # 使用Django模板引擎
        'DIRS': [],                                                    # 模板文件搜索目录（为空则使用默认）
        'APP_DIRS': True,                                              # 是否在应用目录中搜索模板
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # 将request对象传入模板
                'django.contrib.auth.context_processors.auth',  # 将用户认证信息传入模板
                'django.contrib.messages.context_processors.messages',  # 将消息传入模板
            ],
        },
    },
]

# WSGI应用入口，用于部署
WSGI_APPLICATION = 'library_system.wsgi.application'


# 数据库配置
# 参考文档: https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'library',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# 密码验证配置
# 参考文档: https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # 验证密码是否与用户属性（如用户名、邮箱）过于相似
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # 验证密码最小长度
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        # 验证密码是否为常见密码
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # 验证密码是否纯数字
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 国际化配置
# 参考文档: https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'   # 使用简体中文

TIME_ZONE = 'Asia/Shanghai' # 使用上海时区

USE_I18N = True             # 启用国际化支持

USE_TZ = False              # 禁用时区支持（避免MySQL时区问题）


# 静态文件配置（CSS, JavaScript, Images）
# 参考文档: https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'      # 静态文件访问URL前缀