# Generated by Django 6.0.4 on 2026-04-28 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
                ('category', models.CharField(choices=[('literature', '文学'), ('science', '科学'), ('technology', '技术'), ('history', '历史'), ('philosophy', '哲学'), ('art', '艺术'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='可借数量')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('max_borrow_count', models.IntegerField(default=5, verbose_name='最大借阅数')),
                ('current_borrow_count', models.IntegerField(default=0, verbose_name='当前借阅数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '读者',
                'verbose_name_plural': '读者',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借阅日期')),
                ('due_date', models.DateTimeField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还日期')),
                ('status', models.CharField(choices=[('borrowed', '借阅中'), ('returned', '已归还'), ('overdue', '已逾期')], default='borrowed', max_length=10, verbose_name='状态')),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='罚金')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.book', verbose_name='图书')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.reader', verbose_name='读者')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'ordering': ['-borrow_date'],
            },
        ),
    ]
